config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :tasks

  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  validates :name, presence: true
  validates :status, presence: true
  belongs_to :user

  enum status: %i[complete failed in_progress]
  scope :total_complete, -> { where(status: 'complete').length }
  scope :percent, lambda {
                    ((where(status: 'complete').length.to_f / (where(status: 'complete')
                         .length + where(status: 'failed').length).to_f) * 100).to_i
                  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :name, presence: true

  has_many :tasks
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show update edit destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :user_id, :status)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show update edit destroy]

  def index
    @users = User.all
  end

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>

  <%= render 'common/errors', resource: @task %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <p><div class="field">
    <%= form.label :user %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div></p>

  <p><div class="field">
    <%= form.label :status %>
    <%= form.collection_select :status, Task.statuses.map{ |a| [a.first, a.first]}, :first, :second %>
  </div></p>


  <div class="actions">
    <%= form.submit "#{ @task.new_record? ? 'Создать' : 'Изменить' }" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.name %></td>
  <td><%= link_to 'Показать', task %></td>
  <td><%= link_to 'Редактировать', edit_task_path(task) %></td>
  <td><%= link_to 'Удалить', task, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  <td  style="text-align: center"><%= link_to "#{task.status}", edit_task_path(task) %></td>
  <td style="text-align: center"><%= link_to "#{task.user.name}", task.user%>
</tr>

app/views/tasks/edit.html.erb
<h1>Изменить задание</h1>

<%= render 'form' %>

<%= link_to "Список заданий", tasks_path %><br>
<%= link_to "Список пользователей", users_path %><br>
<%= link_to "#{@task.user.name}", @task.user %>

<%= link_to 'Назад', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список заданий</h1>

<table>
  <thead>
    <tr>
      <th>Задания</th>
      <th colspan="3">Функции</th>
      <th>Статус выполнения</th>
      <th>Принадлежит пользователю</th>
    </tr>
  </thead>

  <tbody>

  <%= render @tasks %>

  </tbody>
</table>

<br>

<%= link_to 'Добавить задание', new_task_path %>

app/views/tasks/new.html.erb
<h1>Добавить задание</h1>

<%= render 'form' %>

<%= link_to 'Назад', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название таска:</strong>
  <%= @task.name %>
</p>
<p>
  <%= "Задание принадлежит пользователю: #{@task.user.name}" %>
</p>
<%= link_to "Список заданий", tasks_path %><br>
<%= link_to "Список пользователей", users_path %><br>
<%= link_to "#{@task.user.name}", @task.user %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <%= render 'common/errors', resource: @user %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <p>
    <div class="actions">
      <%= form.submit "#{ @user.new_record? ? 'Создать' : 'Изменить' }" %>
    </div>
  </p>

<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= link_to 'Показать', user %></td>
  <td><%= link_to 'Редактировать', edit_user_path(user) %></td>
  <td><%= link_to 'Удалить', user, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
</tr>

app/views/users/edit.html.erb
<h1>Изменить пользователя</h1>

<%= render 'form' %>

<%= link_to "Список заданий", tasks_path %><br>
<%= link_to "Список пользователей", users_path %><br>

<%= link_to 'Назад', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список пользователей</h1>

<table>
  <thead>
    <tr>
      <th>Имя</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

  <%= render @users %>

  </tbody>
</table>

<br>

<%= link_to 'Добавить пользователя', new_user_path %>

app/views/users/new.html.erb
<h1>Добавить пользователя</h1>

<%= render 'form' %>

<%= link_to 'Назад', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Имя:</strong>
  <%= @user.name %>
</p>
  <% if @user.tasks.empty? %>
    <p>У пользователя нет заданий</p>
  <% else %>
    <p>
      <strong>Количество выполненых заданий: </strong>
      <%= @user.tasks.total_complete %>
    </p>
      <p>
      <strong>Процент выполненых заданий: </strong>
      <% if @user.tasks.empty? %>
        Нет заданий
      <% else %>
        <%= "#{@user.tasks.percent}%" %>
      <% end %>
    </p>

      <table>
      <tr>
        <strong>
          <th>название задания</th>
          <th>статус выполнения</th>
        </strong>
      </tr>
      <% @user.tasks.each do |task| %>
      <tr>
        <td><%= link_to "#{task.name}", edit_task_path(task) %></td>
        <td><%= link_to "#{task.status}", edit_task_path(task) %></td>
      </tr>
      <% end %>
    </table>
  <% end %>
  <p><%= link_to "Добавить задание", new_task_path %></p>

<%= link_to "Назад", users_path %>

app/views/welcome/index.html.erb
<h1>Ласкаво просимо</h1>

<p><%= link_to "Пользователи", users_path %></p>
<p><%= link_to "Задания", tasks_path %></p>